### ISSUE TITLE
SIM_{BEGIN,END} missing from some benchmarks

### ISSUE THREAD

**Issue by BrandonD003** [graphbig/graphBIG#1]
Hi, thanks for releasing your work. I just started running your suite in my timing simulator and I've only looked at a few benchmarks, but I've noticed that some of the CPU benchmarks are missing the calls to SIM_BEGIN and SIM_END. Also, it seems that BFS only calls SIM_BEGIN if there is one thread.

Thanks,
Brandon

**Comment by nailifeng** [comment]
Hi Brandon,
thanks for pointing it out. some of the code is actually in develop branch. I'm working on the merging. The master branch will be updated soon. 
-Lifeng

**Comment by nailifeng** [comment]
develop branch now has been further updated and merged back to master. the SIM annotations should be complete now.
