### ISSUE TITLE
pfm_cxx.h: No such file or directory

### ISSUE THREAD

**Issue by jiangsongHW** [graphbig/graphBIG#3]
when compiling a particular benchmark in ubench_add I got this error message:

myhdfs1:~/opensource/graphBIG-master/benchmark/ubench_add # make all
g++ -c -std=c++0x -Wall -Wno-deprecated -O3 -DUSE_OMP -L../../tools/lib  -I../../common -I../../openG -I../../tools/include ubench_add.cpp
In file included from ../../common/common.h:6,
                 from ubench_add.cpp:6:
../../common/perf.h:18:21: error: pfm_cxx.h: No such file or directory
In file included from ../../common/common.h:6,
                 from ubench_add.cpp:6:
../../common/perf.h: In constructor 'gBenchPerf_event::gBenchPerf_event(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool)':
../../common/perf.h:285: error: 'pfm_instance' was not declared in this scope
../../common/perf.h:285: error: expected `;' before 'pfm'
../../common/perf.h:300: error: 'pfm' was not declared in this scope
make: **\* [ubench_add.o] Error 1

I checked pfm_cxx.h file is under directory ../../tools/pfm_cxx/ but not included in compile arg -I../../tools/include,

is this a bug or something I'm missing?

**Comment by nailifeng** [comment]
Before compiling any particular workload alone, the pfm tools should be first compiled. try "cd graphBIG/tools/" and "make all". 
This procedure will be automatically performed if you call category level makefile (call "make all" in benchmark/ or gpu_bench/). However, for compiling only one workload, it still needs to manually compile tools first.

**Comment by nailifeng** [comment]
Please let me know if this issue is solved or not. Thanks.

**Comment by satanu01** [comment]
When compiling `tools`, facing error . . .

```
/home/..../graphBIG-master/tools/libpfm-4.5.0/lib/../rules.mk:30: recipe for target 'pfmlib_common.o' failed
make[2]: *** [pfmlib_common.o] Error 2
make[2]: *** Waiting for unfinished jobs....
/bin/sh: 1: Syntax error: "(" unexpected
/home/satanu/Downloads/graphBIG-master(1)/graphBIG-master/tools/libpfm-4.5.0/lib/../rules.mk:30: recipe for target 'pfmlib_perf_event_pmu.o' failed
make[2]: *** [pfmlib_perf_event_pmu.o] Error 2
/bin/sh: 1: Syntax error: "(" unexpected
/home/satanu/Downloads/graphBIG-master(1)/graphBIG-master/tools/libpfm-4.5.0/lib/../rules.mk:30: recipe for target 'pfmlib_perf_event.o' failed
make[2]: *** [pfmlib_perf_event.o] Error 2
make[2]: Leaving directory '/home/satanu/Downloads/graphBIG-master(1)/graphBIG-master/tools/libpfm-4.5.0/lib'
Makefile:47: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/satanu/Downloads/graphBIG-master(1)/graphBIG-master/tools/libpfm-4.5.0'
Makefile:10: recipe for target 'lib/libpfm.a' failed
make: *** [lib/libpfm.a] Error 2
```
