### ISSUE TITLE
GraphBIG doesn't work in non-Linux systems

### ISSUE THREAD

**Issue by sampollard** [graphbig/graphBIG#5]
GraphBIG cannot build on BSD-based systems (e.g. MacOS) because it includes `<sys/prctl.h>` which is only available in Linux. Specifically, this is included in 
`graphBIG/tools/include/perfmon/pfmlib_perf_event.h`
and called in
./graphBIG/tools/libpfm-4.5.0/perf_examples/notify_group.c:
./graphBIG/tools/libpfm-4.5.0/perf_examples/self.c:
./graphBIG/tools/libpfm-4.5.0/perf_examples/self_pipe.c:

I got as far as using the `#ifdef __gnu_linux__` but I don't know how to replace the messages being sent by `prctl`.

**Comment by sampollard** [comment]
My mistake. This can be turned off by disabling the profiling code.

**Comment by nailifeng** [comment]
Thanks for pointing it out. I'll add it to the doc soon.
