### ISSUE TITLE
Root > Number of Vertices causes Error

### ISSUE THREAD

**Issue by sampollard** [graphbig/graphBIG#8]
Here is an example. Suppose we have the following graph:

```
printf "SRC,DEST\n1,2\n2,1\n100,1\n" > testdir/edge.csv
printf "ID\n1\n2\n100" > testdir/vertex.csv
```
then run

benchmark/bench_shortestPath --root 100 --dataset testdir

This will give the error
```
wrong source vertex: 100
```

I tried to look into this and the farthest I got was it appears to be something with the find_vertex function on graphs.

**Comment by nailifeng** [comment]
the input for "--root" should be the vertex ID, which is determined by the order in the vertex file and sometimes is different from the "ID" in user perspective. For example, in your case, the vertex ID of "1", "2", "100" are 0, 1, 2 respectively. This is why it complains about the wrong source vertex. 

The openG backend also maintains a map between user-perspective ID to the vertex ID, but in current version, we didn't expose that API to benchmark arguments.
